fix: codegen ts keyword
paritytech/capi pull request #1035
Opened 2023-05-31 19:20 UTC by kratico

2023-05-31 20:09 UTC, ryanleecode approved these changes

2023-06-12 15:34 UTC, tjjfvi requested changes

2023-06-12 15:34 UTC, tjjfvi commented on util/normalize.ts
> +const keywords = ["import"]
```suggestion
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#reserved_words
const keywords = [
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "let",
  "static",
  "yield",
  "await",
  "enum",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
]
```

2023-06-12 16:37 UTC, tjjfvi approved these changes

2023-06-12 16:45 UTC, merged