feat: add kilt example
paritytech/capi pull request #1114
Opened 2023-06-28 16:15 UTC by kratico

2023-06-28 17:03 UTC, harrysolovay commented on examples/kilt/did.eg.ts
> + * @title Kilt decentralized identifier (DID)
```suggestion
 * @title Read Kilt Web3 names and then use them to retrieve DID details
```

2023-06-28 17:04 UTC, harrysolovay requested changes
Actually... perhaps `examples/read/kilt.eg.ts` for now?

2023-06-28 17:08 UTC, kratico commented
Example to get the first 10 owners
```
import { $didPublicKeyDetails, spiritnet } from "@capi/spiritnet"
import { $, ArrayRune, is } from "capi"
import { equals } from "../../deps/std/bytes.ts"

const didPublicKeyDetails = await spiritnet.Web3Names.Owner
  .entries({ limit: 10 })
  .into(ArrayRune)
  .mapArray((entry) =>
    spiritnet.Did.Did
      .value(entry.access(1, "owner"))
      .unhandle(is(undefined))
      .map(({ authenticationKey, publicKeys }) =>
        [...publicKeys.entries()].find(([k, _v]) => equals(k, authenticationKey))
      )
      .unhandle(is(undefined))
  )
  .run()

console.log("DID public key details:", didPublicKeyDetails)
$.assert($.array($.tuple($.sizedUint8Array(32), $didPublicKeyDetails)), didPublicKeyDetails)

2023-06-29 11:46 UTC, harrysolovay commented on examples/read/kilt.eg.ts
> +  .unhandle(is(undefined))
We can probably get rid of this last unhandle

2023-06-29 11:46 UTC, harrysolovay commented on examples/read/kilt.eg.ts
> +const didPublicKeyDetails = await spiritnet.Did.Did
Let's just name this "details" (?)

2023-07-06 14:50 UTC, harrysolovay commented on examples/read/kilt.eg.ts
> +/// Ensure `details` is of the expected shape
```suggestion
/// Ensure `details` is of the expected shape.
```

2023-07-07 11:14 UTC, tjjfvi approved these changes

2023-07-07 15:10 UTC, harrysolovay approved these changes

2023-07-07 15:16 UTC, merged