feat: entry page retrieval
paritytech/capi pull request #644
Opened 2023-02-22 22:40 UTC by harrysolovay

Allows one to retrieve a list of entries as they do a list of keys.

Will soon be complemented by #567.

2023-02-22 22:55 UTC, tjjfvi requested changes
[`state_queryStorageAt` isn't the right method](https://github.com/paritytech/capi/blob/main/rpc/known/state.ts#L200-L207). Looks like we'll either need to use `mapArray` or give up paging and use `state_getPairs`.

2023-02-22 23:05 UTC, harrysolovay commented
This is the same approach used by pjs apps.

> Try reading statemine's uniques classes storage map. Same output.

getPairs is deprecated and calling it results in a server error.

This approach allows for retrieval with 2 round trips... that being said, yea: it's not the prettiest. Not sure if we have any better alternative though.

2023-02-22 23:14 UTC, harrysolovay commented
> The first entry doesn't, but subsequent entries do.

This is interesting. Yea, even if we did go this route, we'd need to skip decoding the subsequent diffs.

2023-02-23 13:45 UTC, tjjfvi approved these changes
Ah, I confused `state_queryStorageAt` with `state_queryStorage`. The former does a single block, the latter is the history-diffing one.

Eventually we should rename `.entry` to `.get` or `.value`, but for now I think we should leave it as-is.

2023-02-23 14:12 UTC, merged