fix: process resource cleanup in start task
paritytech/capi pull request #648
Opened 2023-02-23 13:00 UTC by kratico

Resolves #

- [ ] There is an associated issue (**required**)
- [ ] The change is described in detail
- [ ] There are new or updated tests validating the change (if applicable)

## Description

2023-02-23 17:33 UTC, kratico commented on providers/frame/zombienet.ts
> +        process.kill("SIGINT")
zombienet handles `SIGINT`

https://github.com/paritytech/zombienet/blob/8b421410d803177abe866457443c601dc8b25aae/javascript/packages/cli/src/cli.ts#L298

2023-02-23 20:28 UTC, harrysolovay approved these changes
LGTM

2023-02-23 21:52 UTC, harrysolovay requested changes
Let's actually hold off on merging this, as we will likely want to capture dev process std out for signaling boot progress #649

2023-02-24 12:10 UTC, kratico commented
> Let's actually hold off on merging this, as we will likely want to capture dev process std out for signaling boot progress #649

@harrysolovay 
Do you mean something like `await copy(process.stderr, Deno.stderr)` for the `PolkadotDevProvider`?

2023-02-24 12:37 UTC, harrysolovay commented
Both. I suppose we can tackle that in a subsequent PR. This looks good.

2023-02-24 12:37 UTC, harrysolovay approved these changes

2023-02-24 15:23 UTC, merged